PR to main
stepancar-web-programming/2023-fall-lab-portfolio-nikitin-v.-v. pull request #4
Opened 2023-11-22 17:54 UTC by vladimirwtf

Пожалуйста, примите работу сайта-визитки

2023-11-22 18:05 UTC, vladimirwtf commented
главная index.html находится в папке src

2023-12-06 22:59 UTC, stepancar commented on node_modules/.DS_Store
Пожалуйста, добавьте этот файл в gitignore

2023-12-06 23:00 UTC, stepancar requested changes
ПР содержит закоммиченные node_modules

2023-12-06 23:03 UTC, stepancar commented on src/index.html
> +setInterval(setImage, 1750);
Предлагаю вынести в отдельный файл

2023-12-06 23:04 UTC, stepancar requested changes
ПР не готов к ревью, отформатируйте код, убедитесь что закоммичены только нужные файлы

2024-01-19 15:12 UTC, owlahikit commented
исправления сделаны, пожалуйста, примите работу

2024-01-20 02:58 UTC, stepancar requested changes
Пр содержит конфликты

2024-01-20 02:59 UTC, stepancar commented on node_modules/.DS_Store
Файл не содержит код

2024-01-20 03:00 UTC, stepancar commented on node_modules/.package-lock.json
ПР содержит закоммиченые node_modules

2024-01-20 03:02 UTC, stepancar commented on src/index.html
> +                <button onclick="setNextImage()"
Микс подходов. В одном месте используются стили лежащие в css ту стили захардкожены.

2024-01-20 03:05 UTC, stepancar requested changes
Код не форматирован и другие замечания

Пожалуйста, добавьте в проект линтеры, форматтеры, встройте их в гитхаб экшенс.

2024-01-21 18:02 UTC, owlahikit commented
можно ли мержить?

2024-01-21 19:05 UTC, stepancar commented on src/img/.DS_Store
Файл не содержит код

2024-01-21 19:07 UTC, stepancar requested changes
<img width="1669" alt="Screenshot 2024-01-21 at 11 05 51 AM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-nikitin-v.-v./assets/2854910/dec5b50b-187f-4585-aa62-3e6daed8948f">
Вы не исправили предупреждения линтера

2024-01-21 19:07 UTC, owlahikit commented on src/img/.DS_Store
все ds store удалить?

2024-01-21 19:10 UTC, stepancar commented on .github/workflows/main.yml
> +          node-version: '18.x'
Информацию о версиях nodejs можно найти тут https://nodejs.org/en/about/previous-releases
Не вижу причин использовать 18, если можно взять более новую версию

2024-01-21 19:11 UTC, owlahikit commented on .github/workflows/main.yml
> +          node-version: '18.x'
возможно ли после исправлений все же прийти на экзамен завтра?

2024-01-21 19:14 UTC, stepancar commented on src/styles.css
> +            justify-content: center;
не похоже на автоматическое форматирование. Даже если это оно, в проекте не вижу editor config чтобы это оценить

2024-01-21 19:18 UTC, stepancar commented on src/img/.DS_Store
Хорошая практика, перед отправкой ПР на ревью - просмотреть все изменения, убедиться что все файлы имеют смысл для вашего проекта.
.DS_Store файлы ведь даже не вы создавали, верно? Они пустые, значит на код проекта не влияют. Если поискать информацию о них выяснится что эти файлы имеют смысл только для macos. Все эти факты должны натолкнуть на мысль о том, что эти файлы в гит добавлять не нужно

2024-01-21 19:19 UTC, stepancar commented on src/img/.DS_Store
Чтобы предотвратить случайное добавление в гит, эти файлы должны быть в gitignore

2024-01-21 19:21 UTC, owlahikit commented on src/img/.DS_Store
Исправляю сейчас, спасибо! Абсолютно логичная вещь, сами файлы даже в редакторе не видимы, только в отправке изменений на комите. Раньше не задумывался. Сейчас еще добавлю editor config и исправлю предупреждения линтера

2024-01-21 19:51 UTC, owlahikit commented
выполнил все исправления

2024-01-21 20:07 UTC, stepancar commented on .gitignore
gitignore не может быть пустым. Там , например могут лежать node_modules. DS_Store, etc

2024-01-21 20:08 UTC, stepancar commented on package.json
> +    "eslint-plugin-prettier": "^5.1.3"
это devDepndency, согласны?

2024-01-21 20:12 UTC, stepancar commented on .github/workflows/main.yml
> +          node-version: '21.x'
Ссылка, которую я вам прислал объясняет, что есть версии nodejs с длиннной поддержкой LTS и не с длинной. В продакшене, как правило, принято использовать LTS версии. Это справедливо не только для Nodejs но и для другого ПО. Если вы делаете не эксперименты, советую пользоваться только версиями LTS

2024-01-21 20:37 UTC, stepancar commented on .gitignore
> +src/.DS_Store
DS_Store сам добавляется в разные папки. Если проект большой - такое решение не масштабируемо.
Должен возникнуть вопрос - как сделать чтобы .DS_Store во всех папках был игнорирован.

@vladimirwtf , не торопитесь. спокойно разберитесь во всех наших последних дискуссиях. Вы допущены к экзамену, просто нужно разобраться в вопросах, которые возникли в рамках ПР и доделать.

2024-01-22 11:55 UTC, stepancar commented
@vladimirwtf , жду резолва конфликтов

2024-01-22 20:51 UTC, stepancar approved these changes

2024-01-22 20:51 UTC, merged